version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ld-postgres
    environment:
      - POSTGRES_USER=ld_user
      - POSTGRES_PASSWORD=ld_pass
      - POSTGRES_DB=ld_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
