name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24-dind
        options: --privileged
        ports:
          - 2375:2375
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build all services
        run: docker compose build --parallel

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run healthchecks
        run: |
          # запускаем контейнеры в background
          docker compose up -d auth user diagnostics
          # проверяем эндпоинты
          curl --retry 5 --retry-connrefused http://localhost:4000/health
          curl --retry 5 --retry-connrefused http://localhost:4001/health
          curl --retry 5 --retry-connrefused http://localhost:4002/health
          # останавливаем
          docker compose down

  deploy:
    if: github.event_name == 'push'
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy placeholder
        run: echo "Deploy пока ручной"
