name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  OWNER: ${{ secrets.CR_OWNER }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24-dind
        options: --privileged
        ports:
          - 2375:2375
    env:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_TLS_CERTDIR: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for Docker DIND
        run: |
          for i in {1..15}; do
            docker info && break || sleep 1
          done

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build all services
        run: docker compose build --parallel

      - name: Tag & push images
        run: |
          for svc in auth user diagnostics; do
            IMG=${REGISTRY}/${OWNER}/ld-platform-$svc:latest
            docker tag $svc $IMG
            docker push $IMG
          done

  test:
    needs: build
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24-dind
        options: --privileged
        ports:
          - 2375:2375
    env:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_TLS_CERTDIR: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for Docker DIND
        run: |
          for i in {1..15}; do
            docker info && break || sleep 1
          done

      - name: Build services for test
        run: docker compose build auth user diagnostics

      - name: Start services
        run: docker compose up -d auth user diagnostics

      - name: Run healthchecks
        run: |
          curl --retry 5 --retry-connrefused http://localhost:4000/health
          curl --retry 5 --retry-connrefused http://localhost:4001/health
          curl --retry 5 --retry-connrefused http://localhost:4002/health

      - name: Teardown
        run: docker compose down

  notify:
    if: always()
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        if: ${{ env.SLACK_WEBHOOK_URL != '' }}
        env:
          WEBHOOK: ${{ env.SLACK_WEBHOOK_URL }}
        run: |
          STATUS="✅ SUCCESS"
          if [ "${{ needs.test.result }}" != "success" ]; then STATUS="❌ FAILURE"; fi
          PAYLOAD="{\"text\":\"CI/CD pipeline *${STATUS}* for *${{ github.repository }}* (<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|details>)\"}"
          curl -X POST -H 'Content-Type: application/json' --data "$PAYLOAD" "$WEBHOOK"

  deploy:
    if: github.event_name == 'push'
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy placeholder
        run: echo "Deploy шаг пока ручной"
